# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' La fonction meaps qui distribue tous les actifs en même temps. En entrée, la matrice des distances (et si besoin des odds)
NULL

meaps_all_in <- function(jr_dist, p_dist, xr_dist, emplois, actifs, fuites, parametres, xr_odds, attraction = "constant", group_from = NULL, group_to = NULL, cible = NULL, nthreads = 0L, verbose = TRUE) {
    .Call(`_rmeaps_meaps_all_in`, jr_dist, p_dist, xr_dist, emplois, actifs, fuites, parametres, xr_odds, attraction, group_from, group_to, cible, nthreads, verbose)
}

#' La fonction MEAPS sur plusieurs shufs
NULL

meaps_multishuf_cpp <- function(jr_dist, p_dist, xr_dist, emplois, actifs, fuites, shuf, attraction, parametres, xr_odds, mode = "continu", oddssubjectifs = NULL, nthreads = 0L, verbose = TRUE) {
    .Call(`_rmeaps_meaps_multishuf_cpp`, jr_dist, p_dist, xr_dist, emplois, actifs, fuites, shuf, attraction, parametres, xr_odds, mode, oddssubjectifs, nthreads, verbose)
}

#' La fonction meaps_continu qui ne renvoit que le KL de l'estimation en référence à une distribution connue. 
NULL

#' La fonction meaps_continu qui ne renvoit que le KL de l'estimation en référence à une distribution connue. 
NULL

multishuf_oc_group_cpp <- function(jr_dist, p_dist, xr_dist, emplois, actifs, fuites, shuf, group_from, group_to, parametres, xr_odds, attraction = "constant", cible = NULL, nthreads = 0L, verbose = TRUE) {
    .Call(`_rmeaps_multishuf_oc_group_cpp`, jr_dist, p_dist, xr_dist, emplois, actifs, fuites, shuf, group_from, group_to, parametres, xr_odds, attraction, cible, nthreads, verbose)
}

#'
max_threads <- function() {
    .Call(`_rmeaps_max_threads`)
}

multishuf_oc_cpp <- function(jr_dist, p_dist, xr_dist, emplois, actifs, fuites, shuf, parametres, xr_odds, attraction = "constant", nthreads = 0L, verbose = TRUE) {
    .Call(`_rmeaps_multishuf_oc_cpp`, jr_dist, p_dist, xr_dist, emplois, actifs, fuites, shuf, parametres, xr_odds, attraction, nthreads, verbose)
}

