# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' La fonction meaps qui distribue tous les actifs en même temps. En entrée, la matrice des distances (et si besoin des odds)
NULL

meapsclass <- function(jr_dist, p_dist, xr_dist, emplois, actifs, fuites, parametres, attraction = "constant", group_from = NULL, group_to = NULL, cible = NULL, nthreads = 0L, verbose = TRUE) {
    .Call(`_rmeaps_meapsclass`, jr_dist, p_dist, xr_dist, emplois, actifs, fuites, parametres, attraction, group_from, group_to, cible, nthreads, verbose)
}

